### ISSUE TITLE
About pre-trained models

### ISSUE THREAD

**Issue by Hyeonjoong-Jang** [matsuren/crownconv360depth#2]
Hi,

I appreciate for this nice work.

I was about to try your code, and I noticed that you have not provided any pre-trained models.

Could you please push one of the checkpoints you have?

Or at least could you let me know the required GPU memory or some more information about training?

Thank you.

**Comment by Hyeonjoong-Jang** [comment]
OK, I started to run the train.py code using a command

`python train.py dataset/omnithings`

For those who didn't notice, we should put depth_train_640 folder inside omnithings folder.

dataset_root
|-- omnithings
|    |-- cam1 
|    |-- cam2 
|    |-- ...
|    |-- depth_train_640

But when I run the code, it stopped at a point that it didn't finish one epoch.
I'm figuring out.

![image](https://user-images.githubusercontent.com/55046566/94504851-bb662f80-0244-11eb-83f1-6254b3d869e8.png)

**Comment by matsuren** [comment]
Thank you for your interest in our work!

> In omnithings dataset I downloaded, there were some image files that have four-digit-length names like "0001.png" instead of "00001.png". So I had to handle it

Sorry about that. I forgot that I renamed them. I added instructions in README.md.

I will upload one of the pretrained models soon.

**Comment by matsuren** [comment]
Hi, I uploaded a pre-trained model [here](https://1drv.ms/u/s!Ao6oo2sMuht4tyrqjJbchskcqM-r?e=9TbnH5).  
If you have any other questions, feel free to ask me.

Thanks,

**Comment by matsuren** [comment]
Closing. If you have any other questions, please re-open the issue.
