### ISSUE TITLE
How to get depth image from prediction of model

### ISSUE THREAD

**Issue by alexkrayniy** [matsuren/crownconv360depth#3]
Hi Dear.
I'm trying to run your code. I can run your code successfully and I can see prediction result.
Prediction result is just one dimension array. How can I see depth image from prediction of model?
If I tried to find some code how to convert depth index into depth image, but I couldn't find it.
Please advise me for that.

**Comment by matsuren** [comment]
Thank you for your interest!
I added a script to visualize the estimated depth as an equirectangular depth map. 
Could you try the following command?
```bash
python visualize_depth.py DEPTH_FILE(.npy)
```
Thanks,

**Comment by alexkrayniy** [comment]
Thank you. it works well.
